# Generated by Django 5.1.3 on 2024-11-12 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.TextField()),
                ('Identificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Usuario', models.TextField()),
                ('Rol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
                ('Categorias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libreria.categorias')),
                ('Empleados', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libreria.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('CantidadProductos', models.IntegerField()),
                ('Valor', models.IntegerField()),
                ('Clientes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libreria.clientes')),
                ('MetodoPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libreria.metodopago')),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libreria.productos')),
            ],
        ),
    ]
