# Generated by Django 5.1.3 on 2024-11-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Producto'),
        ),
    ]
